import Head from "next/head";

const LimitedLiabilityCompany = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <div className="LimitedLiabilityCompany">
                <div className="blog-details border-top mt-160 xl-mt-140 pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <div className="blog-post-meta mb-60 lg-mb-40">
                                    {/* <div className="post-info"><a href="blog_02.html">Rashed Kabir .</a> 6 min</div> */}
                                    <h3 className="blog-title">Limited Liability Company</h3>
                                </div>
                            </div>
                        </div>
                        <div className="row gx-xl-5">

                            <div className="col-lg-12">

                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  figurebgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                        <p>Limited Liability Partnership (LLP) is a business structure that combines the advantages of both a partnership and a limited liability company. It allows the partners to have limited liability for their own actions, while at the same time protecting them from being liable for the actions of other partners. The registration of an LLP is relatively simple and straightforward when compared to other business structures.
                                            It offers benefits such as ease of formation, flexibility in management and taxation, limited liability protection, and easy transferability of ownership interests. With these benefits, it is no wonder why many businesses are choosing LLP as their preferred business structure.</p>
                                        <p>LLPs are popular among professional services firms such as accounting, law, and consulting firms as they provide a flexible and efficient way to manage their operations. They also offer tax advantages compared to other structures. Companies looking for an efficient way to register their business should consider an LLP as it can provide them with the legal protection they need while allowing them to operate in an agile manner.</p>
                                        <div className="quote-wrapper">
                                            <div className="icon rounded-circle d-flex align-items-center justify-content-center m-auto"><img src="images/lazy.svg" data-src="images/icon/icon_67.svg" alt="" className="lazy-img" /></div>
                                            <div className="row">
                                                <div className="col-xxl-10 col-xl-11 col-lg-12 col-md-9 m-auto">
                                                    <h4>Quick solutions coupled with extraordinary nice performance—a recommendation that's great.</h4>
                                                </div>
                                            </div>
                                            <h6>James Bond. <span>USA</span></h6>
                                        </div>
                                    </div>
                                </article>
                            </div>
                        </div>

                        <div className="div">
                            <p><b>Annual Clomplience of LLP :</b> </p>
                            <p>
                                LLP (Limited Liability Partnership) is a business structure that offers the benefits of Limited Liability and flexibility of partnership. It is an ideal choice for small businesses or startups who require a certain level of legal protection and flexibility in their operations. <br />
                                Annual compliances are an important part of running a successful LLP. This includes filing annual returns, filing documents with the registrar of companies, maintaining books of accounts and other records as required by law. It is important to ensure that you are compliant with all the regulations set by the government for company incorporation. Failing to comply with these regulations can lead to hefty fines or even closure of your business. Therefore, it is important to keep up-to-date with all the necessary compliances for your LLP on an annual basis.
                            </p>
                            <p>
                                Limited Liability Partnership (LLP) is a form of business entity in India that provides the benefits of limited liability and the flexibility of a partnership. It is important to adhere to all the compliances laid down by the Ministry of Corporate Affairs (MCA) while incorporating an LLP. Annual compliances are one such important aspect that needs to be taken care of for smooth functioning of an LLP.
                            </p>
                            <p>
                                <b>Annual Return Filing :</b> LLPs are required to file their Annual Return in Form 11 with the Registrar of Companies (RoC) within 60 days from the close of the financial year. The Annual Return contains details such as the LLP's name, registered office address, partners' details, and the financial position of the LLP.
                            </p>
                            <p>
                                <b>Financial Statements Filing :</b> LLPs are required to prepare and file their Financial Statements for the financial year ending on March 31st in Form 8 with the Registrar of Companies (RoC) 30th October of each financial year would be the last date to furnish the LLP. If an individual would not able to furnish MCA LLP Form 8 can impose a penalty, penalty depends upon the contributed capital. The Financial Statements include the Balance Sheet, Profit and Loss Account, and the Statement of Changes in Equity.
                            </p>
                            <p>
                                <b>Statutory Audit :</b> LLPs with a turnover of more than Rs. 40 Lakhs or a contribution of more than Rs. 25 lakhs are required to get their accounts audited by a Chartered Accountant. The audit report must be attached with the Financial Statements while filing Form 8.
                            </p>

                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="Rashed Kabir" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="rshdkabir@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}
export default LimitedLiabilityCompany;