import Head from "next/head";

const NidhiRegistration = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-new.jpeg" />
            </Head>
            <div className="NidhiRegistration">
                <div className="blog-details border-top mt-160 xl-mt-140 pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <div className="blog-post-meta mb-60 lg-mb-40">
                                    {/* <div className="post-info"><a href="blog_02.html">Rashed Kabir .</a> 6 min</div> */}
                                    <h3 className="blog-title">Nidhi Company Registration</h3>
                                </div>
                            </div>
                        </div>
                        <div className="row gx-xl-5">
                            <div className="col-lg-12">
                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  figurebgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                        <p>Nidhi Company Registration is a process that enables entrepreneurs to set up and run their own business. It provides the legal framework to ensure that the company is operating in compliance with applicable laws and regulations. The process involves filing of various documents with the Registrar of Companies, obtaining a certificate of incorporation, and registering for taxes.</p>
                                        <div className="quote-wrapper">
                                            <div className="icon rounded-circle d-flex align-items-center justify-content-center m-auto"><img src="images/lazy.svg" data-src="images/icon/icon_67.svg" alt="" className="lazy-img" /></div>
                                            <div className="row">
                                                <div className="col-xxl-10 col-xl-11 col-lg-12 col-md-9 m-auto">
                                                    <h4>Quick solutions coupled with extraordinary nice performance—a recommendation that's great.</h4>
                                                </div>
                                            </div>
                                            <h6>James Bond. <span>USA</span></h6>
                                        </div>
                                        <p> All these steps are necessary for successful company incorporation and operations. With Nidhi Company Registration, entrepreneurs can easily register their companies without any hassle or stress. This will enable them to focus on running their businesses rather than worrying about legal formalities.</p>

                                    </div>
                                </article>
                            </div>
                        </div>

                        <div className="div">
                            <p>
                                <b>Minimum number of members :</b> Nidhi companies must have at least
                                200 members within a year of incorporation.
                            </p>
                            <p>
                                <b>Minimum net owned funds :</b> The minimum net owned funds required to
                                register a Nidhi company is Rs. 10 lakhs.
                            </p>
                            <p>
                                <b>Use of the word 'Nidhi' :</b> The name of the company must include
                                the word 'Nidhi' in its name.
                            </p>
                            <p>
                                <b>Limited operations :</b> Nidhi companies can only operate within the
                                district where they are registered, and they cannot open branches
                                outside the district.
                            </p>
                            <p>
                                <b>Lending restrictions :</b> Nidhi companies cannot lend money to
                                non-members or engage in any other form of business activity other than
                                borrowing and lending with its members.
                            </p>
                            <p>
                                <b>Deposits limits :</b> The maximum limit of deposits that can be
                                accepted from members by a Nidhi company is Rs. 20,000.
                            </p>
                            <p>
                                <b>Prior approval required :</b> Prior approval from the Registrar of
                                Companies (ROC) is required before the company can start accepting
                                deposits.
                            </p>
                            <p>
                                It is essential to comply with all the rules and regulations laid down
                                by the Ministry of Corporate Affairs (MCA) and the Reserve Bank of India
                                (RBI) for the registration and operation of Nidhi companies in India.
                                Failure to comply with these rules may lead to penalties and legal
                                action against the company and its directors.
                                <br />
                                Post incorporation of the Limited Company, within a period of one year
                                from the commencement, the Nidhi Company must meet all of the following
                                criteria:
                            </p>
                            <ul className="style-none list-item">
                                <li>Not have less than two hundred members (shareholders);</li>
                                <li>Have Net Owned Funds (NOF) of ten lakh rupees or more;</li>
                                <li>
                                    Have creative term deposits of not less than ten per cent of the
                                    outstanding deposits; and
                                </li>
                                <li>
                                    Have a ratio of Net Owned Funds to deposits of not more than 1:20.
                                </li>
                            </ul>
                            <p>
                                “Net Owned Funds” means the aggregate of paid-up equity share capital and free reserves as reduced by accumulated losses and intangible assets appearing in the last audited balance sheet.
                            </p>
                            <p>
                                If the Nidhi Company satisfies the above conditions required for operating as a Nidhi Company, the company shall within ninety days from the close of the first financial year after its incorporation and where applicable, the second financial year, file a return of statutory compliances in Form NDH-1 duly certified by a practising CS/CA/CWA along with the requisite fees.
                            </p>
                            <p>
                                In the case at the end one year from commencement the Nidhi Company is not able to meet the above requirement, the Company may within thirty days from the close of the first financial year, apply to the Regional Director in Form NDH-2 for extension of time.
                            </p>
                            <p>
                                If even after the second financial year the Nidhi Company is not able to meet the requirements for a Nidhi Company, then the Nidhi Company shall not accept any further deposits from the commencement of the second financial year till it complies with the provisions for operating as a Nidhi Company and be liable for penal consequences.
                            </p>


                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="Rashed Kabir" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="rshdkabir@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}
export default NidhiRegistration;