import Head from "next/head";

const PrivateLimitedCompany = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-new.jpeg" />
            </Head>
            <div className="privateLimitedCompany">
                <div className="blog-details border-top mt-160 xl-mt-140 pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <div className="blog-post-meta mb-60 lg-mb-40">
                                    {/* <div className="post-info"><a href="blog_02.html">Rashed Kabir .</a> 6 min</div> */}
                                    <h3 className="blog-title">Private Limited Company</h3>
                                </div>
                            </div>
                        </div>
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  privatebgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                        <p>When setting up a private limited company, there are certain documents that need to be submitted by the directors and shareholders. These documents are essential for the incorporation of the company and include important information such as the company's name, registered office address, share capital details, and other pertinent information.</p>
                                        <p>The documents that need to be submitted by directors and shareholders of a private limited company include Articles of Association, Memorandum of Association, application for registration, declaration of compliance with all applicable laws and regulations, appointment forms for directors and secretary (if needed), share allotment forms and other relevant documents. It is important to ensure that all these documents are properly filled out and submitted in order to ensure a successful incorporation process.</p>
                                        <div className="quote-wrapper">
                                            <div className="icon rounded-circle d-flex align-items-center justify-content-center m-auto"><img src="images/lazy.svg" data-src="images/icon/icon_67.svg" alt="" className="lazy-img" /></div>
                                            <div className="row">
                                                <div className="col-xxl-10 col-xl-11 col-lg-12 col-md-9 m-auto">
                                                    <h4>Quick solutions coupled with extraordinary nice performance—a recommendation that's great.</h4>
                                                </div>
                                            </div>
                                            <h6>James Bond. <span>USA</span></h6>
                                        </div>
                                    </div>
                                </article>
                            </div>
                            <div className="col-lg-4">
                                <div className="blog-sidebar dot-bg ms-xxl-4 md-mt-60">
                                    <div className="categories bg-white bg-wrapper mb-30">
                                        <h5 className="mb-20">Category</h5>
                                        <ul className="style-none">
                                            <li><a href="#">Digital  (3)</a></li>
                                            <li><a href="#">Marketing (4)</a></li>
                                            <li><a href="#">Design (2)</a></li>
                                            <li><a href="#">WordPress (8)</a></li>
                                            <li><a href="#">Plugin (5)</a></li>
                                            <li><a href="#">Developer (3)</a></li>
                                            <li><a href="#">Account (7)</a></li>
                                        </ul>
                                    </div>

                                    <div className="recent-news bg-white bg-wrapper mb-30">
                                        <h5 className="mb-20">Recent News</h5>
                                        <div className="news-block d-flex align-items-center pb-25">
                                            <div><img src="images/lazy.svg" data-src="images/blog/blog_img_08.jpg" alt="" className="lazy-img" /></div>
                                            <div className="post ps-4">
                                                <h4 className="mb-5"><a href="blog_details.html" className="title tran3s">10 days quick challenge for boost visitors.</a></h4>
                                                <div className="date">23 July, 2022</div>
                                            </div>
                                        </div>
                                        <div className="news-block d-flex align-items-center pb-25">
                                            <div><img src="images/lazy.svg" data-src="images/blog/blog_img_09.jpg" alt="" className="lazy-img" /></div>
                                            <div className="post ps-4">
                                                <h4 className="mb-5"><a href="blog_details.html" className="title tran3s">Speaking remotely at WordCamp US.</a></h4>
                                                <div className="date">23 July, 2022</div>
                                            </div>
                                        </div>
                                        <div className="news-block d-flex align-items-center">
                                            <div><img src="images/lazy.svg" data-src="images/blog/blog_img_10.jpg" alt="" className="lazy-img" /></div>
                                            <div className="post ps-4">
                                                <h4 className="mb-5"><a href="blog_details.html" className="title tran3s">Monthly Roundup event December 2022.</a></h4>
                                                <div className="date">23 July, 2022</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="keyword bg-white bg-wrapper">
                                        <h5 className="mb-20">Keywords</h5>
                                        <ul className="style-none d-flex flex-wrap">
                                            <li><a href="#">Ideas</a></li>
                                            <li><a href="#">Education</a></li>
                                            <li><a href="#">Design</a></li>
                                            <li><a href="#">Development</a></li>
                                            <li><a href="#">Branding</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="div">
                            <p>
                                <b>Annual Compliances to be complied by Private Limited companies (PLCS)
                                    :
                                </b>
                                Private Limited Companies (PLCs) are required to comply with several
                                annual compliances in India. Here is a list of some of the major annual
                                compliances for Private Limited Companies:
                            </p>
                            <p>
                                <b>Annual General Meeting (AGM) :</b> PLCs are required to hold an AGM
                                every year, within six months from the end of the financial year. The
                                AGM is a forum for shareholders to discuss matters related to the
                                company's performance, elect directors, and approve financial
                                statements.
                            </p>
                            <p>
                                <b>Annual Return Filing :</b> PLCs are required to file their Annual
                                Return in Form MGT-7 with the Registrar of Companies (RoC) within 60
                                days from the closure of the financial year. The Annual Return contains
                                details such as the company's name, registered office address,
                                directors' details, and the financial position of the company. Financial
                                Statements Filing: PLCs are required to prepare and file their Financial
                                Statements for the financial year ending on March 31st in Form AOC-4
                                with the Registrar of Companies (RoC) within 30 days from the due date
                                of Annual General Meeting (AGM). The Financial Statements include the
                                Balance Sheet, Profit and Loss Account, and the Statement of Changes in
                                Equity.
                            </p>
                            <p>
                                <b>Statutory Audit :</b> PLCs are required to get their accounts audited
                                by a Chartered Accountant every year. The audit report must be attached
                                with the Financial Statements while filing Form AOC-4.
                            </p>
                            <p>
                                <b>Income Tax Filing :</b> PLCs are required to file their Income Tax
                                Return (ITR) every year in Form ITR-6 with the Income Tax Department.
                                The due date for filing ITR for PLCs is September 30th of the following
                                financial year. PLCs are also required to obtain a Tax Audit Report from
                                a Chartered Accountant if their turnover exceeds Rs. 1 crore.
                            </p>
                            <p>
                                <b>GST Filing :</b> PLCs registered under the Goods and Services Tax
                                (GST) Act are required to file their GST Returns regularly. The
                                frequency of GST Return filing depends on the turnover of the PLC.
                            </p>
                            <p>
                                <b>TDS Filing :</b> PLCs are required to deduct Tax Deducted at Source
                                (TDS) while making payments to their vendors or suppliers. They are also
                                required to file TDS payments to be done on monthly basis and Returns
                                Quarterly basis.
                            </p>
                            <p>
                                It is important for PLCs to comply with these annual compliances to
                                avoid penalties and legal implications. PLCs can seek professional help
                                Company Secretaries to ensure timely compliance with these requirements.
                            </p>
                            <h5>Documents to be submitted by Directors &amp; Shareholders </h5>
                            <ul className="style-none list-item mt-4">
                                <li>PAN Card (Compulsorily)</li>
                                <li>Voter's ID/Passport/Driver's License (Only any One as ID Proof)</li>
                                <li>
                                    Copy of Latest Bank Statement (not older than 2 months old, to be used
                                    as Address Proof)
                                </li>
                                <li>
                                    Telephone or Mobile Bill/Electricity or Gas Bill (Utility bills) (to
                                    be used as Address Proof)
                                </li>
                                <li>Passport-size photograph (Soft copy)</li>
                                <li>
                                    Copy of Specimen signature (Document shall be shared by us, and to be
                                    signed Directors Only)
                                </li>
                            </ul>

                            <p>
                                <b>NOTE: In case of Having a Valid DIN by the Directors only PAN and
                                    Adhaar is sufficient, it is only for Indian Resident Directors. <br />
                                    In case Directors residing outside India and Foreign nationals to
                                    incorporate a company in India, we urge to speak with professionals.
                                    Our Team of professionals are happy to assist you or guide you.
                                </b>
                            </p>

                            <ul>
                                <li>
                                    Self-attestation must be done by any one of the directors for the
                                    first three documents.
                                </li>

                                <li>
                                    For the foreign nationals, apostilled or notarized copy of the
                                    passport has to be submitted mandatorily. All documents submitted
                                    should be valid.
                                </li>

                                <li>
                                    All the documents must be notarised (if NRI is currently in India or a
                                    Commonwealth country). All the documents must be notarised and
                                    apostille or attested by an Indian embassy (if in a non-Commonwealth
                                    country).
                                </li>
                            </ul>
                            <h5>Documents regarding registered office</h5>
                            <ul className="style-none list-item mt-4">
                                <li>copy of Latest Electricity or Water Bill</li>
                                <li>copy of rental agreement Notarized in English</li>
                                <li>copy of No-objection certificate from the property owner</li>
                                <li>
                                    copy of sale deed/property deed in English (in case of owned property)
                                </li>
                            </ul>
                            <p><b>Establishing up of Foreign Subsidiary:</b></p>
                            <p>
                                Establishing a foreign subsidiary of a private limited company is an
                                important step for business growth and expansion. It helps the company
                                to expand its operations and access new markets, as well as to benefit
                                from various tax advantages. The process of company incorporation
                                involves numerous steps such as selecting the jurisdiction, registering
                                the company, obtaining necessary licenses, and setting up the
                                appropriate corporate structure. Additionally, companies must also
                                consider different legal requirements such as taxation laws and labour
                                regulations in order to ensure compliance with local laws.
                            </p>
                            <p>
                                Establishing a foreign subsidiary of a private limited company is an
                                important step for businesses looking to expand their operations abroad.
                                It allows the parent company to benefit from local resources, access new
                                markets and increase its global presence. Company incorporation involves
                                setting up the legal framework for the foreign subsidiary, including
                                registering it with local authorities, obtaining necessary permits and
                                licenses, and establishing a corporate structure. With the right
                                guidance and expertise, businesses can make this process simpler and
                                more efficient.
                            </p>
                            <p>
                                <b>Setting up a foreign subsidiary in India involves several steps and
                                    legal procedures. Here's a general overview of the process :</b>
                            </p>
                            <p>
                                <b>Choose the type of subsidiary :</b> There are various types of
                                subsidiaries that can be set up in India, including wholly-owned
                                subsidiaries, joint ventures, and limited liability partnerships. Choose
                                the type that best suits your business needs.
                            </p>
                            <p>
                                <b>Reserve a company name :</b> You'll need to reserve a unique name for
                                your subsidiary through the Ministry of Corporate Affairs (MCA) website.
                            </p>
                            <p>
                                <b>Obtain Director Identification Number (DIN's) and Digital Signature
                                    Certificate (DSC's) :</b>
                                The directors of the subsidiary will need to obtain a DIN and DSC from
                                the MCA.
                            </p>
                            <p>
                                <b>Obtain approval from the Reserve Bank of India (RBI) :</b> Depending
                                on the sector you operate in, you may need to obtain approval from the
                                RBI for foreign investment in India.
                            </p>
                            <p>
                                <b>Register the subsidiary :</b> Once the above steps are completed,
                                you'll need to register your subsidiary with the Registrar of Companies
                                (ROC).
                            </p>
                            <p>
                                <b>Obtain tax registration :</b> Register your subsidiary with the tax
                                authorities and obtain a Permanent Account Number (PAN) and Tax
                                Deduction and Collection Account Number (TAN), these shall be given at
                                the time of Incorporation. These numbers will be given or mentioned in
                                the Certificate of Incorporation (COI) itself.
                            </p>
                            <p>
                                <b>Register for Goods and Services Tax (GST) :</b> If your subsidiary
                                will be engaged in the sale of goods or services in India, you'll need
                                to register for GST.
                            </p>
                            <p>
                                <b>Open a bank account :</b> Once the subsidiary is registered, open a
                                bank account in India.
                            </p>
                            <p>
                                <b>Obtain necessary licenses and permits :</b> Depending on the nature
                                of your business, you may need to obtain additional licenses and permits
                                from the relevant authorities.
                            </p>
                            <p>
                                It is highly recommended to consult with a legal professional or a
                                business consultant to ensure that all the legal procedures and
                                requirements are met while setting up a foreign subsidiary in India.
                            </p>
                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="Rashed Kabir" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="rshdkabir@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}
export default PrivateLimitedCompany;