import Head from "next/head";

const NON_Disclosure_Agreement = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <div className="DSC">
                <div className="blog-details border-top mt-160 xl-mt-140 pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <div className="blog-post-meta mb-60 lg-mb-40">
                                    {/* <div className="post-info"><a href="blog_02.html">Rashed Kabir .</a> 6 min</div> */}
                                    <h3 className="blog-title">NON-Disclosure Agreement</h3>
                                </div>
                            </div>
                        </div>
                        <div className="row gx-xl-5">
                            <div className="col-lg-12">
                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  figurebgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                        <p>A non-disclosure agreement (NDA), also known as a confidentiality agreement, is a legally binding contract that establishes a confidential relationship between two or more parties. It is commonly used to protect sensitive or proprietary information shared between the parties, ensuring that the information remains confidential and cannot be disclosed to third parties without proper authorization. NDAs are frequently used in business transactions, employment relationships, and collaborations where the sharing of confidential information is necessary.</p>
                                        <div className="quote-wrapper">
                                            <div className="icon rounded-circle d-flex align-items-center justify-content-center m-auto"><img src="images/lazy.svg" data-src="images/icon/icon_67.svg" alt="" className="lazy-img" /></div>
                                            <div className="row">
                                                <div className="col-xxl-10 col-xl-11 col-lg-12 col-md-9 m-auto">
                                                    <h4>Quick solutions coupled with extraordinary nice performance—a recommendation that's great.</h4>
                                                </div>
                                            </div>
                                            <h6>James Bond. <span>USA</span></h6>
                                        </div>
                                    </div>
                                </article>
                            </div>
                        </div>
                        <div className="div">
                            <p>Here are some key elements typically found in a non-disclosure agreement:</p>
                            <ul>
                                <li><b>Parties:</b> The agreement will identify the parties involved, typically referred to as the "Disclosing Party" and the "Receiving Party." The Disclosing Party is the entity or individual sharing the confidential information, while the Receiving Party is the entity or individual receiving the information.</li>
                                <li><b>Definition of Confidential Information:</b> The agreement will define what constitutes confidential information. This may include any proprietary or sensitive information, trade secrets, technical data, financial information, customer lists, or any other non-public information that the Disclosing Party wishes to protect.</li>
                                <li><b>Obligations of the Receiving Party:</b> The agreement will outline the responsibilities and obligations of the Receiving Party regarding the confidential information.
                                    <p>These obligations typically include:</p>
                                    <ul className="style-none list-item">
                                        <li><b>Non-disclosure:</b> The Receiving Party agrees not to disclose the confidential information to any third party without the prior written consent of the Disclosing Party.</li>
                                        <li><b>Non-use:</b> The Receiving Party agrees not to use the confidential information for any purpose other than the specific purpose outlined in the agreement.</li>
                                        <li><b>Safeguarding:</b> The Receiving Party agrees to take reasonable measures to protect the confidentiality of the information and prevent unauthorized access or disclosure.</li>
                                    </ul>
                                </li>
                                <li><b>Exclusions:</b> The agreement may specify certain information that is not considered confidential or subject to the obligations of the NDA. This typically includes information that is already publicly known or independently developed by the Receiving Party without the use of the confidential information.</li>
                                <li><b>Term and Termination:</b> The NDA will specify the duration of the agreement, known as the term. It may also outline circumstances under which the agreement can be terminated, such as by mutual agreement, completion of the specific purpose, or a breach of the agreement by either party.</li>
                                <li><b>Remedies and Dispute Resolution:</b> The agreement may address the remedies available in case of a breach, such as injunctive relief or monetary damages. It may also specify the method of dispute resolution, such as arbitration or litigation.</li>
                                <li><b>Governing Law and Jurisdiction:</b> The NDA will specify the governing law that applies to the agreement and the jurisdiction where any disputes will be resolved.</li>
                            </ul>
                            <p>It's important to note that the specific terms and provisions of an NDA can vary depending on the context and the requirements of the parties involved. It is advisable to consult with a legal professional to draft or review an NDA to ensure it meets the specific needs and legal requirements of your situation.</p>
                            <p><b>Note: Reach our Legal team to help you on Drafting.</b></p>
                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="Rashed Kabir" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="rshdkabir@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}
export default NON_Disclosure_Agreement;