import Head from "next/head";

const ShopAct = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-new.jpeg" />
            </Head>
            <div className="DSC">
                <div className="blog-details border-top mt-160 xl-mt-140 pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <div className="blog-post-meta mb-60 lg-mb-40">
                                    {/* <div className="post-info"><a href="blog_02.html">Rashed Kabir .</a> 6 min</div> */}
                                    <h3 className="blog-title">Shops and Establishment / Labor License</h3>
                                </div>
                            </div>
                        </div>
                        <div className="row gx-xl-5">
                            <div className="col-lg-12">
                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  figurebgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                        <p>In India, the Shops and Establishments Act is a state-specific legislation that regulates the working conditions, employment terms, and rights of employees in shops, commercial establishments, and other businesses. The act is aimed at ensuring the welfare and safety of workers.</p>
                                        <div className="quote-wrapper">
                                            <div className="icon rounded-circle d-flex align-items-center justify-content-center m-auto"><img src="images/lazy.svg" data-src="images/icon/icon_67.svg" alt="" className="lazy-img" /></div>
                                            <div className="row">
                                                <div className="col-xxl-10 col-xl-11 col-lg-12 col-md-9 m-auto">
                                                    <h4>Quick solutions coupled with extraordinary nice performance—a recommendation that's great.</h4>
                                                </div>
                                            </div>
                                            <h6>James Bond. <span>USA</span></h6>
                                        </div>
                                        <p>The process of obtaining a Shops and Establishment or Labor License may vary slightly from state to state, as the act is implemented by individual state governments. However, the general steps involved are as follows:</p>
                                    </div>
                                </article>
                            </div>
                        </div>

                        <div className="div">
                        <p><b>Application Form:</b> Self explanatory webform available in the official site.</p>
      <p><b>Required Documents:</b> Prepare the necessary documents for the license application. The typical documents required include:</p>
      <ul className="style-none list-item">
        <li>Identity proof of the employer (Proprietor, Partners, or Directors).</li>
        <li>Address proof of the establishment.</li>
        <li>Registration certificate of the business entity (if applicable).</li>
        <li>Proof of ownership or possession of the premises (rental agreement or property documents).</li>
        <li>Details of the nature of business and activities carried out.</li>
        <li>Details of employees, such as their names, addresses, and employment terms.</li>
        <li>Any other specific documents required by the state's labour department.</li>
      </ul >
      <p><b>Fill Out the Application:</b> Complete the application form with accurate information and ensure that all required fields are filled.</p>
      <p><b>Submit the Application:</b> Submit the filled application form along with the necessary documents to the local labour department or the designated authority specified by the state.</p>
      <p><b>Payment of Fees:</b> Pay the prescribed license fee as specified by the state government. The fee may vary based on factors such as the number of employees, the nature of the establishment, and the state's regulations.</p>
      <p><b>Fee Details</b></p>
      <table className="table table-bordered table-responsive">
        <tbody>
          <tr>
            <td></td>
            <td colSpan={2}><p>Fees Structure for obtaining Registration Certificate</p></td>
          </tr>
          <tr>
            <td>1</td>
            <td>0 Employees	</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 100/-	</td>
          </tr>
          <tr>
            <td>2</td>
            <td>1-5 Employees	</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 500/-	</td>
          </tr>
          <tr>
            <td>3</td>
            <td>6-10 Employees	</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 1000/-	</td>
          </tr>
          <tr>
            <td>4</td>
            <td>11-20 Employees	</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 2000/-	</td>
          </tr>
          <tr>
            <td>5</td>
            <td>21-50 Employees	</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 5000/-	</td>
          </tr>
          <tr>
            <td>6</td>
            <td>51-100 Employees	</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 10,000/-	</td>
          </tr>
          <tr>
            <td>7</td>
            <td>101 and Above Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 10,000/- + 5000 for additional 50 Persons.</td>
          </tr>
        </tbody>
      </table>
      <p><b>Annual Fee Payment Timelines</b></p>
      <table className="table table-bordered table-responsive">
        <tbody>
          <tr>
            <td></td>
            <td colSpan={2}><p>For Payments</p></td>
          </tr>
          <tr>
            <td>1</td>
            <td>Between 1st November to 1st December</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i>No Penalty</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Between 2nd December to 31st December</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i>25% Penalty</td>
          </tr>
          <tr>
            <td>3</td>
            <td>After 31st December</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i>50% Penalty</td>
          </tr>
        </tbody>
      </table>
      <p><b>Contract Labour Act (Principal Employer) - Registration</b></p>
      <p>Every Shop and Establishments in State of Telangana Should Register under Principal Employer under Contract Labour Act</p>
      <p><b>Procedure:</b></p>
      <table className="table table-bordered table-responsive">
        <thead>
          <tr>
            <th>Steps</th>
            <th>Forms</th>
            <th>Documents to be Attached</th>
            <th>Fee</th>
            <th>Timelines</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Submit</td>
            <td>Online application form "Form I"</td>
            <td>*Follow Checklist below</td>
            <td>Online fee payment (As per the fee structure given below)</td>
            <td>30 days as from the date of submission of the application as per 
              Citizen's Charter. Deemed Registration at the end of 30 days from Application if no adverse orders passed</td>
          </tr>
          <tr>
            <td>Issue</td>
            <td>Form II</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
      <p><b>Checklist</b></p>
      <table className="table table-bordered table-responsive">
        <tbody>
          <tr>
            <td>1</td>
            <td>1	Form No-I i.e Application for Registration</td>
          </tr>
          <tr>
            <td>2</td>
            <td>List of Contractors including details such as 1). Name and address of the contractor, 2). Nature of Work, 3). No.of Contract Labour engaged and
              4). Date of commencement of contract work.
              </td>
          </tr>
          <tr>
            <td>3</td>
            <td>Form No.-VI B i.e. Notice of Commence of Contract Work by the Principal Employer in</td>
          </tr>
        </tbody>
      </table>
      <p><b>Fee Details</b></p>
      <table className="table table-bordered table-responsive">
        <tbody>
          <tr>
            <td></td>
            <td><b>Fees Structure for obtaining Registration certificate</b></td>
          </tr>
          <tr>
            <td>1</td>
            <td>5-20 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 500/-</td>	
          </tr>
          <tr>
            <td>2</td>
            <td>21-50 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 1,000/-</td>	
          </tr>
          <tr>
            <td>3</td>
            <td>51-100 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 2,000/-</td>	
          </tr>
          <tr>
            <td>4</td>
            <td>101- 200 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 5,000/-</td>	
          </tr>
          <tr>
            <td>5</td>
            <td>201-400 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 10,000/-</td>	
          </tr>
          <tr>
            <td>6</td>
            <td>401 and above Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 15,000/-</td>	
          </tr>
        </tbody>
      </table>
      <p><b>Contract Labour Act (Contractor) – License</b></p>
      <table className="table table-bordered table-responsive">
        <thead>
          <tr>
            <th>S.no</th>
            <th>Forms</th>
            <th>Documents to be Attached</th>
            <th>Fee</th>
            <th>Timelines</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Online application form "Form IV"</td>
            <td>*Follow Checklist below</td>
            <td>Online fee payment (As per the fee structure given below)</td>
            <td>30 Days from the date of submission of complete application as per Citizen's Charter. Deemed Registration at the end of 30 days from date of application if no adverse orders passed</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Form VI</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
      <p>System sends SMS to respective applicant at each progression.</p>
      <p>In case of any clarifications, the applicant is informed on actions to be taken and start date will be after all the clarifications have been received.</p>
      <p>Online application process requires no physical touch point.</p>
      <p><b>Checklist</b></p>
      <table className="table table-bordered table-responsive">
        <thead>
          <tr>
            <th>S.no</th>
            <th>Particulars</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1.</td>
            <td>Form No-IV i.e Application for License</td>
          </tr>
          <tr>
            <td>2.</td>
            <td>Copy of Form No.II i.e copy of certificate of Registration granted to the Principal Employer</td>
          </tr>
          <tr>
            <td>3.</td>
            <td>Form No.V- i.e. Certificate by the Principal Employer.</td>
          </tr>
          <tr>
            <td>4.</td>
            <td>Form No.VI A- i.e Notice of commencement of contract work by the contractor</td>
          </tr>
          <tr>
            <td>5.</td>
            <td>Copy of agreement or work order entered in between the Principal Employer and contractor</td>
          </tr>
          <tr>
            <td>6.</td>
            <td>Joint Undertaking both by Principal Employer and Contractor stating for payment of notified minimum wages to the contract labour engaged by them.</td>
          </tr>
        </tbody>
      </table>
      <p><b>Fee Details</b></p>
      <table className="table table-borderd table-responsive">
        <thead>
          <tr>
            <th></th>
            <th colSpan={2}>Fees Structure for obtaining Licence</th>
          </tr>
          <tr>
            <td>1</td>
            <td>5-20 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 350/-</td>	
          </tr>
          <tr>
            <td>2</td>
            <td>21-50 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 500/-</td>	
          </tr>
          <tr>
            <td>3</td>
            <td>51-100 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 1,000/-</td>	
          </tr>
          <tr>
            <td>4</td>
            <td>101-200 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 2,500/-</td>	
          </tr>
          <tr>
            <td>5</td>
            <td>201-400 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 5,000/-</td>	
          </tr>
          <tr>
            <td>6</td>
            <td>401 and above Employees -</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 7,500/-</td>	
          </tr>
          <tr>
            <td></td>
            <td colSpan={2}>Security deposit challan-Every contractor shall deposit an amount of Rs.500/- for each contract labour towards Security Deposit in SBH, where treasury transactions are undertaken.</td>
          </tr>
        </thead>
      </table>
      <p><b>Contract Labour Act (Contractor) - Annual Fee Payment</b></p>
      <table className="table table-bordered table-responsive">
        <thead>
          <tr>
            <th>Steps</th>
            <th>Forms</th>
            <th>Documents to be Attached</th>
            <th>Fee</th>
            <th>Timelines</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Submit</td>
            <td>Online application form "Form VII"</td>
            <td>*Follow Checklist below</td>
            <td>Online fee payment (As per the fee structure given below)</td>
            <td>System Generates Auto-Renewal Certificate in form VII Immediately</td>
          </tr>
          <tr>
            <td>Issue</td>
            <td>Form VI</td>
            <td>None</td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
      <p>System sends SMS and eMail to respective applicant at each progression.</p>
      <p>In case of any clarifications, the applicant is informed on actions to be taken and start date will be after all the clarifications have been received.</p>
      <p>Online application process requires no physical touch point.</p>
      <p><b>Steps to follow Auto-Renewal of Licence</b></p>
      <table className="table table-bordered table-responsive">
        <tbody>
          <tr>
            <td>1.</td>
            <td>Enter your existing licence number</td>
          </tr>
          <tr>
            <td>2.</td>
            <td>Validate the details of the licence, if they are found correct</td>
          </tr>
          <tr>
            <td>3.</td>
            <td>Verify the Annual Fee payable.</td>
          </tr>
          <tr>
            <td>4.</td>
            <td>Proceed to pay the Annual fee</td>
          </tr>
          <tr>
            <td>5.</td>
            <td>Acknowledgement and auto -renewal certificate will be generated immediately</td>
          </tr>
          <tr>
            <td>6.</td>
            <td>Print both and preserve them for your reference</td>
          </tr>
        </tbody>
      </table>
      <p><b>Fee Details</b></p>
      <table className="table table-borderd table-responsive">
        <thead>
          <tr>
            <th></th>
            <th colSpan={2}>Fees Structure for obtaining Auto-Renewal certificate of Licence</th>
          </tr>
          <tr>
            <td>1</td>
            <td>5-20 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 350/-</td>	
          </tr>
          <tr>
            <td>2</td>
            <td>21-50 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 500/-</td>	
          </tr>
          <tr>
            <td>3</td>
            <td>51-100 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 1,000/-</td>	
          </tr>
          <tr>
            <td>4</td>
            <td>101-200 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 2,500/-</td>	
          </tr>
          <tr>
            <td>5</td>
            <td>201-400 Employees</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 5,000/-</td>	
          </tr>
          <tr>
            <td>6</td>
            <td>401 and above Employees -</td>
            <td><i className="fa fa-inr" aria-hidden="true"></i> 7,500/-</td>	
          </tr>
        </thead>
      </table>
      <p><b>Verification and Inspection:</b> The labour department may conduct an inspection of the establishment to verify the details provided in the application. They may also inspect the premises for compliance with labour laws and regulations.</p>
      <p><b>Issuance of License:</b> If the labour department is satisfied with the application and inspection, they will issue the Shops and Establishment or Labor License. This license is typically valid for a specific period and needs to be renewed periodically, as per the state's regulations.</p>
      <p>It's important to note that the process and requirements may differ among states, so it is advisable to consult the specific state's labour department or seek guidance from a legal professional or labour consultant to ensure compliance with the local regulations.</p>
      <p>Additionally, labour laws and regulations are subject to change, so it's essential to stay updated with the latest provisions and amendments introduced by the respective state government.</p>
                         

                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="Rashed Kabir" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="rshdkabir@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}
export default ShopAct;