import Head from "next/head";


import Image from "next/image";
import bg from '../assets/img/hero/hero-pattern-bg-2.jpg'
import hat from '../assets/img/icon/hat-b.svg'
import hatv from '../assets/img/icon/hat.svg'
import book from '../assets/img/icon/book.svg'
import mainhero from '../assets/img/hero/hero-main-img-3.png'
import shape1 from '../assets/img/hero/hero-thumb-1.jpg'
import st1 from '../assets/img/chose/st-1.jpg'
import st2 from '../assets/img/chose/st-2.jpg'
import st3 from '../assets/img/chose/st-3.jpg'
import st4 from '../assets/img/chose/st-4.jpg'
import shape4 from '../assets/img/shape/pattern-2.svg'
import course1 from '../assets/img/icon/course-icon-1.svg'
import course2 from '../assets/img/icon/course-icon-2.svg'
import course3 from '../assets/img/icon/course-icon-3.svg'
import course4 from '../assets/img/icon/course-icon-4.svg'
import course5 from '../assets/img/icon/course-icon-5.svg'
import course6 from '../assets/img/icon/course-icon-6.svg'
import course7 from '../assets/img/icon/course-icon-7.svg'
import course8 from '../assets/img/icon/course-icon-8.svg'

import about4 from '../assets/img/about/about-4.png'
import aboutthumb from '../assets/img/about/about-thumb-2.jpg'
import shaperound from '../assets/img/shape/bg-round-shape-1.svg'
import icon1 from '../assets/img/icon/icon-1.svg'
import videoimg from '../assets/img/video/video-img-3.jpg'
import countersvg from '../assets/img/icon/about-us-counter-1.svg'
import countersvg2 from '../assets/img/icon/about-us-counter-2.svg'
import countersvg3 from '../assets/img/icon/about-us-counter-3.svg'
import choose4 from '../assets/img/chose/chose-4.svg'
import choose5 from '../assets/img/chose/chose-5.svg'
import choose6 from '../assets/img/chose/chose-6.jpg'
import choose7 from '../assets/img/chose/chose-7.jpg'
import vector from '../assets/img/icon/Vector.svg'
import thumb19 from '../assets/img/course/course-thumb-19.jpg'
import doc2 from '../assets/img/icon/document-2.svg'
import user3 from '../assets/img/icon/3-User.svg'
import thumb20 from '../assets/img/course/course-thumb-20.jpg'
import thumb21 from '../assets/img/course/course-thumb-21.jpg'
import thumb22 from '../assets/img/course/course-thumb-22.jpg'
import studentrepo from '../assets/img/hero/student-repot.png'

import partner11 from '../assets/img/brand/partner-11.svg'
import partner12 from '../assets/img/brand/partner-12.svg'
import partner13 from '../assets/img/brand/partner-13.svg'
import partner14 from '../assets/img/brand/partner-14.svg'
import partner15 from '../assets/img/brand/partner-15.svg'


import tauthor5 from '../assets/img/testimonial/t-author-5.png'
import tauthor6 from '../assets/img/testimonial/t-author-6.png'
import tshape1 from '../assets/img/testimonial/t-shape-1.png'
import blog19 from '../assets/img/blog/blog-19.jpg'
import blog20 from '../assets/img/blog/blog-20.jpg'
import blog21 from '../assets/img/blog/blog-21.jpg'
import blogauthor from '../assets/img/blog/blog-author-1.jpg'
import archieve from '../assets/img/icon/archive.svg'
import filter2 from '../assets/img/icon/filter-2.svg'






import useAOS from "../hooks/useAOS";


export default function Home() {

  useAOS({
    offset: 200,
    duration: 600,
    easing: 'ease-in-sine',
    delay: 100,
  });

  return (
    <>
      <Head>
        <title>Rediger App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="" style={{overflow:"hidden"}}>

        <div className="hero-section-3 pt-85 pb-40" style={{
          backgroundImage: `url(${bg.src})`,
          width: '100%',
          height: '100%',
        }} >
          <div className="s-shape-1">
            <Image src={hat} alt="icon" />
          </div>
          <div className="s-shape-2">
            <Image src={book} alt="icon" />
            {/* <Image src="assets/img/icon/book.svg" alt="icon"/> */}
          </div>
          <div className="container">
            <div className="row align-items-center">
              <div className="col-xl-6 col-lg-7">
                <div className="hero-content-3 text-lg-start text-center">
                  <div className="sub-title">
                    <p>Start To New Journey</p>
                  </div>
                  <div className="title">
                    <h1>We take care of All your business compliance needs!</h1>
                  </div>
                  <div className="description">
                    <p>An online business compliance platform that helps entrepreneurs and other individuals with various, registrations, tax filings, and other legal matters.</p>
                  </div>
                  <div className="theme-btn">
                    <a href="signup.html">Register Now</a>
                  </div>
                </div>
              </div>
              <div className="col-xl-6 col-lg-5 text-center mt-lg-50 mt-md-50 mt-xs-50">
                <div className="hero-thumb-3">
                  <div className="thumb">
                    <Image src={mainhero} alt="thumb" />
                    <div className="bubble-bg-1"></div>
                    <div className="bubble-bg-2"></div>
                    <div className="bubble-bg-3"></div>
                  </div>
                  <div className="shape-1">
                    <Image src={shape1} alt="thumb" />
                  </div>
                  <a href="signup.html" className="join-btn">
                    Join <br /> Now
                  </a>
                  <div className="student-thumbs">
                    <h4>1000+ Happy
                      Customers</h4>
                    <div className="student-thumbs-box">
                      <span><Image src={st1} alt="thumb" /></span>
                      <span><Image src={st2} alt="thumb" /></span>
                      <span><Image src={st3} alt="thumb" /></span>
                      <span><Image src={st4} alt="thumb" /></span>
                      <span className="add-more"><i className="fa-solid fa-plus"></i></span>
                    </div>
                  </div>
                  <div className="shape-4">
                    <Image src={shape4} alt="thumb" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="course-section-3 pt-150 pb-150 pt-lg-120 pb-lg-120 pt-md-80 pb-md-80 pt-xs-50 pb-xs-50">
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-xl-5 col-lg-7 col-md-10">
                    <div className="section-title text-center mb-50 aos-init " data-aos="fade-up" data-aos-delay="200">
                        <div className="title">
                            <h2>Our Services</h2>
                        </div>
                        {/* <div className="description">
                            <p>On the other hand, we denounce with righteous indignation and is dislike men who
                                are
                                so
                                beguiled .</p>
                        </div> */}
                    </div>
                </div>
            </div>

            <div className="row feature-layout mt-50">
                <div className="col-xl-3 col-md-6">
                    <div className="feature-wrap-3" data-aos="fade-up" data-aos-delay="200">
                        <div className="icon">
                            <Image src={course1} alt="icon"/>
                        </div>
                        <div className="title">
                            <h3>Private Limited company</h3>
                        </div>
                        <div className="text">
                            <p>Beginner Diploma In Basic English
                                Grammar</p>
                        </div>
                    </div>
                </div>
                <div className="col-xl-3 col-md-6">
                    <div className="feature-wrap-3" data-aos="fade-up" data-aos-delay="200">
                        <div className="icon">
                            <Image src={course2} alt="icon"/>
                        </div>
                        <div className="title">
                            <h3>Fssai Registration</h3>
                        </div>
                        <div className="text">
                        <p>Completed Landing Page Design &
                        Conversion Rate 2022</p>
                        </div>
                    </div>
                </div>
                <div className="col-xl-3 col-md-6">
                    <div className="feature-wrap-3" data-aos="fade-up" data-aos-delay="200">
                        <div className="icon">
                            <Image src={course3} alt="icon"/>
                        </div>
                        <div className="title">
                            <h3>Limited Liability Company</h3>
                        </div>
                        <div className="text">
                            <p>Join Our Training Course &
                                Build Your Skill.</p>
                        </div>
                    </div>
                </div>
                <div className="col-xl-3 col-md-6">
                    <div className="feature-wrap-3" data-aos="fade-up" data-aos-delay="200">
                        <div className="icon">
                            <Image src={course4} alt="icon"/>
                        </div>
                        <div className="title">
                            <h3>Sole Proprietorship</h3>
                        </div>
                        <div className="text">
                            <p>Completed Landing Page Design &
                                Conversion Rate 2022</p>
                        </div>
                    </div>
                </div>
                <div className="col-xl-3 col-md-6">
                    <div className="feature-wrap-3" data-aos="fade-up" data-aos-delay="250">
                        <div className="icon">
                            <Image src={course5} alt="icon"/>
                        </div>
                        <div className="title">
                            <h3>Msme Registration</h3>
                        </div>
                        <div className="text">
                            <p>Completed Landing Page Design &
                                Conversion Rate 2022</p>
                        </div>
                    </div>
                </div>
                <div className="col-xl-3 col-md-6">
                    <div className="feature-wrap-3" data-aos="fade-up" data-aos-delay="250">
                        <div className="icon">
                            <Image src={course6} alt="icon"/>
                        </div>
                        <div className="title">
                            <h3>One person Company</h3>
                        </div>
                        <div className="text">
                            <p>Completed Landing Page Design &
                                Conversion Rate 2022</p>
                        </div>
                    </div>
                </div>
                <div className="col-xl-3 col-md-6">
                    <div className="feature-wrap-3" data-aos="fade-up" data-aos-delay="250">
                        <div className="icon">
                            <Image src={course7} alt="icon"/>
                        </div>
                        <div className="title">
                            <h3>Partnership Firm</h3>
                        </div>
                        <div className="text">
                            <p>Beginner Diploma In Basic English
                                Grammar - Better Search</p>
                        </div>
                    </div>
                </div>
                <div className="col-xl-3 col-md-6">
                    <div className="feature-wrap-3" data-aos="fade-up" data-aos-delay="250">
                        <div className="icon">
                            <Image src={course8} alt="icon"/>
                        </div>
                        <div className="title">
                            <h3>Provident Fund</h3>
                        </div>
                        <div className="text">
                            <p>Join Our Training Course &
                                Build Your Skill.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div className="about-section-3 pt-80 pb-lg-80 pb-md-80 pt-xs-50 pb-xs-50">
        <div className="shape-1">
            <Image src={book} alt="shape"/>
        </div>
        <div className="shape-2">
            <Image src={hat} alt="shape"/>
        </div>
        <div className="container">
            <div className="row align-items-center">
                <div className="col-lg-6 text-center mb-lg-50 mb-md-50 mb-xs-50">
                    <div className="about-thumb-3">
                        <div className="thumb">
                            <Image className="w-100" src={about4} alt="thumb"/>
                        </div>
                        <div className="round-thumb">
                            <Image src={aboutthumb} alt="thumb"/>
                        </div>
                        <div className="round-bg-shape">
                            <Image className="img-fluid" src={shaperound} alt="shape"/>
                        </div>
                        <div className="history-box text-start">
                            <div className="icon">
                                <Image src={icon1} alt="icon"/>
                            </div>
                            <h6 className="exp-title">25+ Years Experience</h6>
                        </div>
                        <div className="course-count-section">
                            <div className="course-count">
                                <div className="number">
                                    <h6 className="odometer" data-count="535">000</h6>
                                </div>
                                <span className="count-mark">+</span>
                                <p>Services</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-6">
                    <div className="about-content-3 ps-xxl-5" data-aos="fade-left" data-aos-delay="200">
                        <div className="section-title">
                            <div className="sub-title">
                                <p>About Our Company</p>
                            </div>
                            <div className="title">
                                <h2>We Have Best Experts who can guide you</h2>
                            </div>
                        </div>
                        <div className="description">
                            <p>Our All-In-One Platform And Team Of Experts Will Help Direct You In The Right Path.</p>
                        </div>
                        <div className="list">
                            <ul>
                                <li>
                                    <i className="fa-light fa-square-check"></i>
                                    <span>Best Support</span>
                                </li>
                                <li>
                                    <i className="fa-light fa-square-check"></i>
                                    <span>Service From Expert</span>
                                </li>
                                <li>
                                    <i className="fa-light fa-square-check"></i>
                                    <span>Highly Experienced</span>
                                </li>
                                <li>
                                    <i className="fa-light fa-square-check"></i>
                                    <span>350+ Filings</span>
                                </li>
                            </ul>
                        </div>
                        <div className="theme-btn">
                            <a href="contact.html">Book Appointment</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <div className="video-section-3 pt-150 pt-lg-120 pt-md-80 pt-xs-50">
        <div className="container">
            <div className="row">
                <div className="col-xl-12">
                    <div className="section-title text-center mb-50">
                        <div className="sub-title mb-10" data-aos="fade-up" data-aos-delay="150">
                            <p>Registered Customers</p>
                        </div>
                        <div className="title" data-aos="fade-up" data-aos-delay="200">
                            <h2>It’s easy To Register</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div className="row">
                <div className="col-xl-12">
                    <div className="video-wrapper" data-aos="fade-up" data-aos-delay="300">
                        <div className="thumb">
                            <Image className="w-100" src={videoimg} alt="video"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div className="counter-section-3 pt-80 pb-100 pb-lg-90 pb-md-50 pt-xs-50 pb-xs-20">
        <div className="container">
            <div className="row text-center">
                <div className="col-lg-3 col-md-6">
                    <div className="counter-wrap-3 mb-30" data-aos="fade-up" data-aos-delay="200">
                        <div className="icon">
                            <Image src={countersvg} alt="icon"/>
                        </div>
                        <div className="counter-info">
                            <div className="number">
                                <h3 className="odometer" data-count="14,500">00</h3>
                            </div>
                            <div className="counter-separator"></div>
                            <div className="text">
                                <p>Happy Customers</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-3 col-md-6">
                    <div className="counter-wrap-3 mb-30" data-aos="fade-up" data-aos-delay="250">
                        <div className="icon">
                            <Image src={countersvg2} alt="icon"/>
                        </div>
                        <div className="counter-info">
                            <div className="number">
                                <h3 className="odometer" data-count="569">00</h3>
                            </div>
                            <div className="counter-separator"></div>
                            <div className="text">
                                <p>Good Comment</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-3 col-md-6">
                    <div className="counter-wrap-3 mb-30" data-aos="fade-up" data-aos-delay="300">
                        <div className="icon">
                            <Image src={countersvg3} alt="icon"/>
                        </div>
                        <div className="counter-info">
                            <div className="number">
                                <h3 className="odometer" data-count="32,500">00</h3>
                            </div>
                            <div className="counter-separator"></div>
                            <div className="text">
                                <p>Services Download</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-3 col-md-6">
                    <div className="counter-wrap-3 mb-30" data-aos="fade-up" data-aos-delay="350">
                        <div className="icon">
                            <Image src={vector} alt="icon"/>
                        </div>
                        <div className="counter-info">
                            <div className="counter-inner">
                                <div className="number">
                                    <h3 className="odometer" data-count="32">00</h3>
                                </div>
                                <span className="counter-quantity">k</span>
                            </div>
                            <div className="counter-separator"></div>
                            <div className="text">
                                <p>Best Awards</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <div className="career-section-3 pt-80 pb-50">
        <div className="container">
            <div className="row">
                <div className="col-xl-12">
                    <div className="section-title text-center mb-50">
                        <div className="sub-title mb-10" data-aos="fade-up" data-aos-delay="150">
                            <p>Choose Your Career</p>
                        </div>
                        <div className="title" data-aos="fade-up" data-aos-delay="200">
                            <h2>Discover Your Gain</h2>
                        </div>
                    </div>
                </div>
            </div>

            <div className="row">
                <div className="col-xl-6 col-lg-6">
                    <div className="career-wrap" data-aos="fade-up" data-aos-delay="300">
                        <div className="thumb">
                            <Image src={choose4} alt="chose"/>
                        </div>
                        <div className="content">
                            <p>Start From Today</p>
                            <h4>
                                <a href="#">Join Our Group & Build Your Career.</a>
                            </h4>
                            <a className="read-more" href="#">Join Now</a>
                        </div>
                    </div>
                </div>
                <div className="col-xl-6 col-lg-6">
                    <div className="career-wrap" data-aos="fade-up" data-aos-delay="300">
                        <div className="thumb">
                            <Image src={choose5} alt="chose"/>
                        </div>
                        <div className="content">
                            <p>Build Your Career</p>
                            <h4>
                                <a href="#">Educating You Early & Improving your Growth</a>
                            </h4>
                            <a className="read-more" href="#">Join Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {/* <div className="course-list-section pt-150 pb-120 pt-lg-120 pb-lg-90 pt-md-80 pb-md-50 pt-xs-50 pb-xs-20">
        <div className="container">
            <div className="row">
                <div className="col-xl-12">
                    <div className="section-title text-center mb-50">
                        <div className="sub-title mb-10" data-aos="fade-up" data-aos-delay="150">
                            <p>Our Services</p>
                        </div>
                        <div className="title" data-aos="fade-up" data-aos-delay="200">
                            <h2>Most Popular Services</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div className="row justify-content-center">
                <div className="col-lg-6 col-md-6">
                    <div className="course-list-content mb-30" data-aos="fade-up" data-aos-delay="250">
                        <div className="course-img">
                            <Image src={thumb19} alt="thumb"/>
                        </div>
                        <div className="course-content-list">
                            <div className="course-meta">
                                <div className="category">
                                    <div className="cat-1">
                                        <a href="#">Internet</a>
                                    </div>
                                    <div className="cat-2">
                                        <a href="#">Merketing</a>
                                    </div>
                                </div>
                                <div className="price">$19.00</div>
                            </div>
                            <div className="course-list-title">
                                <a href="course-details.html">The Most Complete Design Thinking Online
                                    Course On The Market</a>
                            </div>
                            <div className="course-meta-bottom">
                                <span>
                                    <Image src={doc2} alt="icon"/>
                                    10 Lesson
                                </span>
                                <span>
                                    <Image src={user3} alt="icon"/>
                                    64 Students
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-6 col-md-6">
                    <div className="course-list-content mb-30" data-aos="fade-up" data-aos-delay="300">
                        <div className="course-img">
                            <Image src={thumb20} alt="thumb"/>
                        </div>
                        <div className="course-content-list">
                            <div className="course-meta">
                                <div className="category">
                                    <div className="cat-1">
                                        <a href="#">Design</a>
                                    </div>
                                    <div className="cat-2">
                                        <a href="#">Development</a>
                                    </div>
                                </div>
                                <div className="price">$29.99</div>
                            </div>
                            <div className="course-list-title">
                                <a href="course-details.html">Language Page Design &amp;Conversion Rate Is
                                    Course On The Market</a>
                            </div>
                            <div className="course-meta-bottom">
                                <span>
                                    <Image src={doc2} alt="icon"/>
                                    12 Lesson
                                </span>
                                <span>
                                    <Image src={user3} alt="icon"/>
                                    64 Students
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-6 col-md-6">
                    <div className="course-list-content mb-30" data-aos="fade-up" data-aos-delay="350">
                        <div className="course-img">
                            <Image src={thumb21} alt="thumb"/>
                        </div>
                        <div className="course-content-list">
                            <div className="course-meta">
                                <div className="category">
                                    <div className="cat-1">
                                        <a href="#">Intermediate</a>
                                    </div>
                                    <div className="cat-2">
                                        <a href="#">Expert</a>
                                    </div>
                                </div>
                                <div className="price">$12.19</div>
                            </div>
                            <div className="course-list-title">
                                <a href="course-details.html">The Challenge Of Global Learning Public is
                                    Education</a>
                            </div>
                            <div className="course-meta-bottom">
                                <span>
                                <Image src={doc2} alt="icon"/>
                                    24 Lesson
                                </span>
                                <span>
                                <Image src={user3} alt="icon"/>
                                    64 Students
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-6 col-md-6">
                    <div className="course-list-content mb-30" data-aos="fade-up" data-aos-delay="400">
                        <div className="course-img">
                            <Image src={thumb22} alt="thumb"/>
                        </div>
                        <div className="course-content-list">
                            <div className="course-meta">
                                <div className="category">
                                    <div className="cat-1">
                                        <a href="#">Language </a>
                                    </div>
                                    <div className="cat-2">
                                        <a href="#">English</a>
                                    </div>
                                </div>
                                <div className="price">$29.00</div>
                            </div>
                            <div className="course-list-title">
                                <a href="course-details.html">Beginner Diploma In English Grammar On Online
                                    Education</a>
                            </div>
                            <div className="course-meta-bottom">
                                <span>
                                <Image src={doc2} alt="icon"/>
                                    25 Lesson
                                </span>
                                <span>
                                <Image src={user3} alt="icon"/>
                                    64 Students
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> */}
    <div className="choose-section-3 overflow-hidden pt-80 pb-80 pt-xs-50 pb-xs-50">
        <div className="container">
            <div className="row align-items-center justify-content-center">
                <div className="col-xl-6 col-lg-6">
                    <div className="about-us-choose-content" data-aos="fade-right" data-aos-delay="200">
                        <div className="section-title">
                            <div className="sub-title mb-10">
                                <p>Why Choose Us</p>
                            </div>
                            <div className="title">
                                <h2>Start New business On Your Own</h2>
                            </div>
                        </div>
                        <div className="text">
                            <p>The standard chunk of Ipsum since the reproduced below for those interested.
                                Sections
                                and
                                from
                            </p>
                        </div>
                        <div className="list">
                            <ul>
                                <li>
                                    <i className="fa-regular fa-square-check"></i>
                                    <span>Consultation from Industry Experts.</span>
                                </li>
                                <li>
                                    <i className="fa-regular fa-square-check"></i>
                                    <span>Value For Money and hassle free service.</span>
                                </li>
                                <li>
                                    <i className="fa-regular fa-square-check"></i>
                                    <span>10 Lakh++ Happy Customers.</span>
                                </li>
                                <li>
                                    <i className="fa-regular fa-square-check"></i>
                                    <span>Money Back Guarantee.</span>
                                </li>
                            </ul>
                        </div>
                        <div className="choose-btn-2">
                            <div className="theme-btn">
                                <a href="contact.html">Get Started</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-xl-6 col-lg-6 text-center mt-md-50 mt-xs-50">
                    <div className="choose-3-thumb">
                        <div className="thumb">
                            <Image className="w-100" src={choose7} alt="thumb"/>
                        </div>
                        <div className="thumb-2" data-aos="zoom-in" data-aos-delay="200">
                            <Image src={choose6} alt="thumb"/>
                        </div>
                        <div className="student-report">
                            <Image src={studentrepo} alt="thumb"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        {/* <div className="partner-section-3 pt-60 pb-60" data-aos="fade-up" data-aos-delay="200">
        <div className="container">
            <div className="row text-center">
                <div className="col-xl-12">
                    <div className="swiper brand-layout-2">
                        <div className="swiper-wrapper">
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner11} alt="thumb"/>
                                </div>
                            </div>
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner12} alt="thumb"/>
                                </div>
                            </div>
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner13} alt="thumb"/>
                                </div>
                            </div>
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner14} alt="thumb"/>
                                </div>
                            </div>
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner15} alt="thumb"/>
                                </div>
                            </div>
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner11} alt="thumb"/>
                                </div>
                            </div>
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner12} alt="thumb"/>
                                </div>
                            </div>
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner11} alt="thumb"/>
                                </div>
                            </div>
                            <div className="swiper-slide">
                                <div className="brand-item">
                                    <Image src={partner12} alt="thumb"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> */}
    <div className="testimonial-section-3 pt-150 pb-50 pt-lg-120 pb-lg-120 pt-md-80 pb-md-80 pt-xs-50 pb-xs-50">
        <div className="container">
            <div className="row align-items-center">
                <div className="col-xl-6 col-lg-6 text-lg-start text-center mb-md-50 mb-xs-50">
                    <div className="testimonial-thumb-3" data-aos="fade-right" data-aos-delay="200">
                        <div className="thumb">
                            <Image src={tauthor5} alt="thumb"/>
                        </div>
                        <div className="shape-1">
                            <Image src={tauthor6} alt="thumb"/>
                        </div>
                        <div className="shape-2">
                            <Image src={tshape1} alt="shape"/>
                        </div>
                    </div>
                </div>
                <div className="col-xl-6 col-lg-6">
                    <div className="swiper testimonial-slider-active-3">
                        <div className="swiper-wrapper">
                            <div className="swiper-slide single-slide">
                                <div className="testimonial-content-3">
                                    <div className="icon">
                                        <Image src={vector} alt="icon"/>
                                    </div>
                                    <div className="text">
                                        <p>Rediger is a renowned group of individual professionals that has established itself as a market leader in guiding corporate houses and entrepreneurs. We specialize in Company Incorporation, Tax, and all other services rendered by professionals independently. We assist entrepreneurs and start-ups in providing consultations for their businesses. We have a tailor-made solution in the best interests of your business, and we provide a guaranteed and satisfactory service.
                                      </p>
                                    </div>
                                    <div className="name">
                                        <h3>Vijendra</h3>
                                    </div>
                                    <div className="info">
                                        <p>General Manager & CEO</p>
                                    </div>
                                </div>
                            </div>
                            <div className="swiper-slide single-slide">
                                <div className="testimonial-content-3">
                                    <div className="icon">
                                        <Image src={vector} alt="icon"/>
                                    </div>
                                    <div className="text">
                                        <p>Objectively redefine out the box technologie multimedia based
                                            networks.
                                            Education Proactively is architect economically sound synergy
                                            progressive value a time online Authoritatively engage is
                                            out-of-the-box
                                            users for interoperable core competencies. Appropriately pontificate
                                            of.</p>
                                    </div>
                                    <div className="name">
                                        <h3>Davied Jone</h3>
                                    </div>
                                    <div className="info">
                                        <p>General Manager & CEO</p>
                                    </div>
                                </div>
                            </div>
                            <div className="swiper-slide single-slide">
                                <div className="testimonial-content-3">
                                    <div className="icon">
                                        <Image src={vector} alt="icon"/>
                                    </div>
                                    <div className="text">
                                        <p>Objectively redefine out the box technologie multimedia based
                                            networks.
                                            Education Proactively is architect economically sound synergy
                                            progressive value a time online Authoritatively engage is
                                            out-of-the-box
                                            users for interoperable core competencies. Appropriately pontificate
                                            of.</p>
                                    </div>
                                    <div className="name">
                                        <h3>Davied Jone</h3>
                                    </div>
                                    <div className="info">
                                        <p>General Manager & CEO</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="swiper-pagination-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {/* <div className="blog-grid-section-3 pt-80 pb-80 pt-xs-50 pb-xs-50">
        <div className="container">
            <div className="row">
                <div className="col-xl-12">
                    <div className="section-title text-center mb-50">
                        <div className="sub-title mb-10" data-aos="fade-up" data-aos-delay="150">
                            <p>Our Recent Articles</p>
                        </div>
                        <div className="title" data-aos="fade-up" data-aos-delay="200">
                            <h2>Latest Blog & News</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div className="row align-items-center justify-content-center">
                <div className="col-lg-4 col-md-6">
                    <div className="blog-wrap-3 mb-30" data-aos="fade-up" data-aos-delay="250">
                        <div className="blog-img">
                            <Image src={blog19} alt="blog"/>
                        </div>
                        <div className="content">
                            <div className="meta">
                                <a href="#">
                                    <Image src={hatv} alt="icon"/>
                                    Education
                                </a>
                            </div>
                            <h3 className="title">
                                <a href="blog-details.html">
                                    Educating Your Child Early & Take
                                    Spread Knowledge
                                </a>
                            </h3>
                            <div className="info">
                                <div className="thumb">
                                    <Image src={blogauthor} alt="icon"/>
                                    <div className="name">
                                        <h4>Mili Smith</h4>
                                    </div>
                                </div>
                                <a href="#">
                                    <Image src={archieve} alt="icon"/>
                                    21 Jan 2023
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 col-md-6">
                    <div className="blog-wrap-3 mb-30" data-aos="fade-up" data-aos-delay="300">
                        <div className="blog-img">
                            <Image src={blog20} alt="blog"/>
                        </div>
                        <div className="content">
                            <div className="meta">
                                <a href="#">
                                    <Image src={hatv} alt="icon"/>
                                    Learning
                                </a>
                            </div>
                            <h3 className="title">
                                <a href="blog-details.html">
                                    Online Education Also & Take The
                                    Knowledge
                                </a>
                            </h3>
                            <div className="info">
                                <div className="thumb">
                                    <Image src={blogauthor} alt="blog"/>
                                    <div className="name">
                                        <h4>Creation</h4>
                                    </div>
                                </div>
                                <a href="#">
                                    <Image src={archieve} alt="icon"/>
                                    21 Jan 2023
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 col-md-6">
                    <div className="blog-wrap-3 mb-30" data-aos="fade-up" data-aos-delay="350">
                        <div className="blog-img">
                            <Image src={blog21} alt="blog"/>
                        </div>
                        <div className="content">
                            <div className="meta">
                                <a href="#">
                                    <Image src={filter2} alt="blog"/>
                                    Art & Design
                                </a>
                            </div>
                            <h3 className="title">
                                <a href="blog-details.html">
                                    Art & Design Your Early & Improve
                                    Spread Skills.
                                </a>
                            </h3>
                            <div className="info">
                                <div className="thumb">
                                    <Image src={blogauthor} alt="blog"/>
                                    <div className="name">
                                        <h4>Hardson</h4>
                                    </div>
                                </div>
                                <a href="#">
                                    <Image src={archieve} alt="icon"/>
                                    21 Jan 2023
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="row text-center mt-20">
                <div className="col-xl-12">
                    <div className="theme-btn" data-aos="fade-up" data-aos-delay="200">
                        <a href="blog-classNameic.html">Read All Blogs</a>
                    </div>
                </div>
            </div>
        </div>
    </div> */}

    <div className="faq-section pt-20 pb-100 pt-lg-100 pb-lg-100 pt-md-80 pb-md-80 pt-xs-50 pb-xs-50">
        <div className="container">
            <div className="row">
                <div className="col-xl-12">
                    <div className="faq-wrapper">
                        <div className="row">
                            <div className="col-xl-5 col-lg-6 mb-md-50 mb-xs-50">
                                <div className="contract-phone" data-aos="fade-right">
                                    <div className="title">
                                        <h2>Get In Touch</h2>
                                    </div>
                                    <form action="#">
                                        <div className="input-wrap">
                                            <input type="text" placeholder="Phone"/>
                                        </div>
                                        <div className="input-wrap">
                                            <input type="text" placeholder="Email"/>
                                        </div>
                                        <div className="input-wrap">
                                            <input type="text" placeholder="Location"/>
                                        </div>
                                        <div className="input-wrap">
                                            <textarea placeholder="Write Messeage"></textarea>
                                        </div>
                                        <div className="submit-btn">
                                            <button type="submit">Submit Request</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div className="col-xl-7 col-lg-6">
                                <div className="faq-content-wrap">
                                    <div className="section-title mb-50">
                                        <div className="sub-title mb-10">
                                            <p>Frequently Asked Question</p>
                                        </div>
                                        <div className="title">
                                            <h2>Have Your Any Question?</h2>
                                        </div>
                                    </div>

                                    <div className="faq-accordion" id="accordionExample">
                                        <div className="accordion-item">
                                            <h2 className="accordion-header">
                                                <button className="accordion-button" type="button"
                                                    data-bs-toggle="collapse" data-bs-target="#collapseOne"
                                                    aria-expanded="true" aria-controls="collapseOne">
                                                    How Can I Register?
                                                </button>
                                            </h2>
                                            <div id="collapseOne" className="accordion-collapse collapse show"
                                                data-bs-parent="#accordionExample">
                                                <div className="accordion-body">
                                                    Globally engineer high-payoff potentialities with impactful
                                                    e-business. Interactively leverage existing
                                                    backward-compatible
                                                    ideas with user-centric e-services. Globally enhance.
                                                </div>
                                            </div>
                                        </div>
                                        <div className="accordion-item">
                                            <h2 className="accordion-header">
                                                <button className="accordion-button collapsed" type="button"
                                                    data-bs-toggle="collapse" data-bs-target="#collapseTwo"
                                                    aria-expanded="false" aria-controls="collapseTwo">
                                                    What Is Process To Get Expert Team?
                                                </button>
                                            </h2>
                                            <div id="collapseTwo" className="accordion-collapse collapse"
                                                data-bs-parent="#accordionExample">
                                                <div className="accordion-body">
                                                    Globally engineer high-payoff potentialities with impactful
                                                    e-business. Interactively leverage existing
                                                    backward-compatible
                                                    ideas with user-centric e-services. Globally enhance.
                                                </div>
                                            </div>
                                        </div>
                                        <div className="accordion-item">
                                            <h2 className="accordion-header">
                                                <button className="accordion-button collapsed" type="button"
                                                    data-bs-toggle="collapse" data-bs-target="#collapseThree"
                                                    aria-expanded="false" aria-controls="collapseThree">
                                                    How Does About Online Services?
                                                </button>
                                            </h2>
                                            <div id="collapseThree" className="accordion-collapse collapse"
                                                data-bs-parent="#accordionExample">
                                                <div className="accordion-body">
                                                    Globally engineer high-payoff potentialities with impactful
                                                    e-business. Interactively leverage existing
                                                    backward-compatible
                                                    ideas with user-centric e-services. Globally enhance.
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="theme-btn mt-50">
                                        <a href="#">Add Questions</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {/* <div className="subscribe-section bg-white pb-md-80 pb-xs-50">
        <div className="container">
            <div className="row">
                <div className="col-xl-12">
                    <div className="subscribe-wrapper" data-aos="fade-up" data-aos-delay="200">
                        <div className="row align-items-center">
                            <div className="col-xl-7 col-lg-6">
                                <div className="subscribe-title text-lg-start text-center">
                                    <h3>Subscribe To Our Newsletter</h3>
                                </div>
                            </div>
                            <div className="col-xl-5 col-lg-6 mt-md-30 mt-xs-30">
                                <div className="subscribe-form text-lg-start text-center">
                                    <form action="#">
                                        <div className="input-wrap">
                                            <input type="email" placeholder="Enter Your Mail"/>
                                            <button type="submit">Subscribe</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> */}

    
      
      </div>
    </>
  );
}
