import mainbgImg from "../../assets/images/portalRediger/mainBGImage.jpeg"
import Image from "next/image";
import icon07 from "../../assets/images/portalRediger/createAccount.jpeg"
import icon08 from "../../assets/images/portalRediger/findService.jpeg"
import icon09 from "../../assets/images/portalRediger/quickProcess.jpeg"
import shape1 from "../../assets/images/shape/shape_01.svg"
import Head from "next/head";



const AboutUs = () => {
    return(
        <>
              <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
    <div className="aboutUs">
    <div className="inner-banner-one inner-banner bg-pink text-center z-1 pt-160 lg-pt-130 pb-160 xl-pb-120 md-pb-80 position-relative">
			<div className="container">
                <h3 className="mb-35 xl-mb-20 pt-15">About Rediger</h3>
                {/* <ul className="theme-breadcrumb style-none d-inline-flex align-items-center justify-content-center position-relative z-1 bottom-line">
                    <li><a href="index.html">Home</a></li>
                    <li>/</li>
                    <li> About us</li>
                </ul> */}
			</div>
			{/* <Image src={mainbgImg}  alt="" className="lazy-img shapes w-100 illustration" style={{height:"-webkit-fill-available"}}/> */}
		</div>

        <div className="block-feature-two mt-150 xl-mt-100">
			<div className="container">
				<div className="row gx-xl-5">
					<div className="col-lg-6 wow fadeInLeft">
						<div className="me-xxl-4">
                            <div className="title-one mb-60 lg-mb-40">
                                <div className="upper-title">About us</div>
                                <h3>Consultation <span>from<img src="images/lazy.svg" data-src="images/shape/title_shape_06.svg" alt="" className="lazy-img"/></span> Industry Experts.</h3>
                                <p className="fs-22">Our founders Dustin Moskovitz and Justin Rosenstein met while leading Engineering .</p>
                            </div>
                            <a href="contact.html" className="btn-two">Contact Us</a>
                            <div className="counter-wrapper border-top pt-40 md-pt-10 mt-65 md-mt-40">
                                <div className="row">
                                    <div className="col-xxl-6 col-sm-5">
                                        <div className="counter-block-one mt-20">
                                            <div className="main-count fw-500 color-dark"><span className="counter">1.2</span>%</div>
                                            <span>Low interest rate</span>
                                        </div>
                                    </div>
                                    <div className="col-xxl-6 col-sm-7">
                                        <div className="counter-block-one mt-20">
                                            <div className="main-count fw-500 color-dark">$<span className="counter">1.3</span>b+</div>
                                            <span>Cumulative trading volume</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
					</div>
					<div className="col-lg-6 wow fadeInRight">
						<div className="block-two md-mt-40">
							<div className="bg-wrapper">
								<h5>Who we are?</h5>
								<p className="fs-22 lh-lg mt-20">Hailing from Hyderabad, India, Vijendra & Co was incorporated under the leading light of highly experienced and veteran professionals. The company came into existence with a view to provide broad spectrum of quality professional services in the domain of Corporate Management Consultancy.
                                Over the years, with utmost dedication, we have been successfully serving the clientele with the unparalleled services that has helped us to boast our prominent position in the market.</p>
								<h5 className="top-line">Our Mission </h5>
								<p className="fs-22 lh-lg mt-20">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod incididunt ut labore et dolore aliqua. </p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

        <div className="video-banner-one mt-150 xl-mt-120 md-mt-80">
            <div className="container">
                <div className="bg-wrapper position-relative z-1 overflow-hidden d-flex align-items-center justify-content-center videoBgImg">
                    <a className="fancybox video-icon d-flex align-items-center justify-content-center rounded-circle tran3s" data-fancybox="" href="https://www.youtube.com/embed/aXFSJTjVjw0">
                        <i className="fa-solid fa-play"></i>
                    </a>
                </div>
            </div>
        </div>

        {/* <div className="block-feature-five position-relative z-1 pt-170 xl-pt-120 pb-130 xl-pb-100 lg-pb-80">
			<div className="container">
				<div className="row">
					<div className="col-xl-8 m-auto">
						<div className="title-one text-center mb-35 lg-mb-20">
							<h3>We’r here to help <br/> you get your <span>dream home<img src="images/lazy.svg" data-src="images/shape/title_shape_07.svg" alt="" className="lazy-img"/></span></h3>
							<p className="fs-24 color-dark">It’s easy to start with us with these simple steps</p>
						</div>
					</div>
				</div>
				<div className="row justify-content-between">
					<div className="col-xxl-11 m-auto">
						<div className="row gx-xl-5 justify-content-center">
							<div className="col-lg-4 col-sm-6">
								<div className="card-style-one text-center wow fadeInUp mt-40">
									<img src="images/lazy.svg" data-src="images/icon/icon_07.svg" alt="" className="lazy-img m-auto icon"/>
									<h5 className="mt-50 lg-mt-30 mb-15">Create Account</h5>
									<p className="pe-xxl-4 ps-xxl-4">It’s very easy to open an account and start your journey.</p>
								</div>
							</div>
							<div className="col-lg-4 col-sm-6">
								<div className="card-style-one text-center wow fadeInUp mt-40 arrow position-relative" data-wow-delay="0.1s">
									<img src="images/lazy.svg" data-src="images/icon/icon_08.svg" alt="" className="lazy-img m-auto icon"/>
									<h5 className="mt-50 lg-mt-30 mb-15">Find Home</h5>
									<p className="pe-xxl-4 ps-xxl-4">Complete your profile with all the info to get attention of client.</p>
								</div>
							</div>
							<div className="col-lg-4 col-sm-6">
								<div className="card-style-one text-center wow fadeInUp mt-40" data-wow-delay="0.2s">
									<img src="images/lazy.svg" data-src="images/icon/icon_09.svg" alt="" className="lazy-img m-auto icon"/>
									<h5 className="mt-50 lg-mt-30 mb-15">Quick Process</h5>
									<p className="pe-xxl-4 ps-xxl-4">Apply & get your preferable jobs with all the requirements and get it.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<img src="images/lazy.svg" data-src="images/shape/shape_07.svg" alt="" className="lazy-img shapes shape_01"/>
			<img src="images/lazy.svg" data-src="images/shape/shape_08.svg" alt="" className="lazy-img shapes shape_02"/>
		</div> */}

<div className="block-feature-five position-relative z-1 pt-100 lg-pt-80 pb-130 xl-pb-100 lg-pb-80 mt-150 xl-mt-200 lg-mt-150">
                <div className="container">
                    <div className="row">
                        <div className="col-xl-8 m-auto">
                            <div className="title-one text-center mb-35 lg-mb-20">
                                <h3>Security, Confidentiality & Results Fine Home  <br /> <span>–Find Service <Image src={shape1} alt="" className="lazy-img" /></span></h3>
                                <p className="fs-24 color-dark">Find your required service and make payment.</p>
                            </div>
                        </div>
                    </div>
                    <div className="row justify-content-between">
                        <div className="col-xxl-11 m-auto">
                            <div className="row gx-xl-5 justify-content-center">
                                <div className="col-lg-4 col-sm-6">
                                    <div className="card-style-one text-center wow fadeInUp mt-40">
                                        <Image src={icon07} alt="" className="lazy-img m-auto icon border-img" style={{height:"auto"}} />
                                        <h5 className="mt-50 lg-mt-30 mb-15">Create Account</h5>
                                        <p className="pe-xxl-4 ps-xxl-4">It’s very easy to open an account and start your journey.</p>
                                    </div>
                                </div>
                                <div className="col-lg-4 col-sm-6">
                                    <div className="card-style-one text-center wow fadeInUp mt-40 arrow position-relative" data-wow-delay="0.1s">
                                        <Image src={icon08} alt="" className="lazy-img m-auto icon border-img" style={{height:"auto"}}/>
                                        <h5 className="mt-50 lg-mt-30 mb-15">Find Service</h5>
                                        <p className="pe-xxl-4 ps-xxl-4">Complete your profile with all the info to get attention of client.</p>
                                    </div>
                                </div>
                                <div className="col-lg-4 col-sm-6">
                                    <div className="card-style-one text-center wow fadeInUp mt-40" data-wow-delay="0.2s">
                                        <Image src={icon09} alt="" className="lazy-img m-auto icon border-img" style={{height:"auto"}} />
                                        <h5 className="mt-50 lg-mt-30 mb-15">Quick Process</h5>
                                        <p className="pe-xxl-4 ps-xxl-4">Our team will coordinate you and update your requirement status.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <img src="images/lazy.svg" data-src="images/shape/shape_07.svg" alt="" className="lazy-img shapes shape_01" />
                <img src="images/lazy.svg" data-src="images/shape/shape_08.svg" alt="" className="lazy-img shapes shape_02" />
            </div>






    </div>
        </>
    )
}
export default AboutUs;