import Head from "next/head";
import Link from "next/link";

const ESIS = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-new.jpeg" />
            </Head>
            <div className="DSC">
                <div className="inner-banner-one inner-banner bg-pink text-center z-1 pt-160 lg-pt-130 pb-80 xl-pb-80 md-pb-60 position-relative">
                    <div className="container">
                        <h3 className="mb-35 xl-mb-20 pt-15">ESIS</h3>
                        <ul className="theme-breadcrumb style-none d-inline-flex align-items-center justify-content-center position-relative z-1 bottom-line">
                            <li><Link href={'/'}>Home</Link></li>
                            <li>/</li>
                            <li>ESIS</li>
                        </ul>
                    </div>
                </div>
                <div className="blog-details border-top pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  esisbgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                    </div>
                                </article>
                            </div>
                            <div className="col-lg-4">
                                <div className="blog-sidebar dot-bg ms-xxl-4 md-mt-60">
                                    <div className="categories bg-white bg-wrapper mb-30">
                                        <h5 className="mb-20">Other Services</h5>
                                        <ul className="style-none">
                                            <li><Link href={"/services/GST_Registration/GST_registration"}>GST Registration</Link></li>
                                            <li><Link href={"/services/GST_Registration/LUT_filing_Under_GST"}>LUT Filling Under GST</Link></li>
                                            <li><Link href={"/services/GST_Registration/TDS-ReturnFiling"}>TDS Return Filing</Link></li>
                                            <li><Link href={"/services/GST_Registration/professionalTax_Registration"}>Professional Tax Registration</Link></li>
                                            <li><Link href={"/services/GST_Registration/providentFund"}>Provident Fund</Link></li>
                                            {/* <li><Link href={"/services/GST_Registration/ESIS"}>ESIS</Link></li> */}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="div">
                            <p>ESIS is a social security scheme provided to employees in India. It is governed by the Employees' State Insurance Act, 1948, and is managed by the Employees' State Insurance Corporation (ESIC), a statutory body under the Ministry of Labour and Employment, Government of India</p>
                            <p>Here are some of the key features and provisions of the ESI scheme:</p>
                            <p>
                                <b>Applicability :</b> The ESI scheme is applicable to factories and establishments employing 10 or more employees with a salary up to Rs. 21,000 per month. The scheme is also applicable to certain categories of establishments as notified by the government.
                            </p>
                            <p>
                                <b>Contributions :</b> Both the employer and the employee are required to make monthly contributions to the ESI fund. The contribution rate for the employee is 0.75% of the gross salary, while the employer contributes 3.25% of the employee's gross salary.
                            </p>
                            <p>
                                <b>Benefits :</b> The ESI scheme provides medical, sickness, maternity, disability, and dependent benefits to the employees and their families. The benefits include medical treatment, hospitalization, cash benefits during sickness, maternity leave, and pension in case of disability or death.
                            </p>
                            <p>
                                <b>ESI card :</b> Every employee enrolled under the ESI scheme is issued an ESI card, which is used to avail of medical benefits at the ESI dispensaries and hospitals.
                            </p>
                            <p>
                                <b>Compliance :</b> Employers are required to register under the ESI scheme, obtain a code number, and maintain various registers and records related to ESI contributions and benefits. Employers who fail to comply with the provisions of the ESI Act can be penalized and prosecuted.
                            </p>
                            <p>
                                <b>Audit :</b> The ESIC conducts audits of the ESI contributions and benefits provided by the employer to ensure compliance with the provisions of the ESI Act.
                            </p>
                            <p>
                                The ESI scheme is an important social security measure for employees in India, providing access to medical care and financial support during periods of illness or disability.
                            </p>
                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="User Name" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="username@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}
export default ESIS;