import Head from "next/head";
import Link from "next/link";

const LUT_Under_GSt = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-new.jpeg" />
            </Head>
            <div className="DSC">
                <div className="inner-banner-one inner-banner bg-pink text-center z-1 pt-160 lg-pt-130 pb-80 xl-pb-80 md-pb-60 position-relative">
                    <div className="container">
                        <h3 className="mb-35 xl-mb-20 pt-15">LUT Filling Under GST</h3>
                        <ul className="theme-breadcrumb style-none d-inline-flex align-items-center justify-content-center position-relative z-1 bottom-line">
                            <li><Link href={'/'}>Home</Link></li>
                            <li>/</li>
                            <li>LUT Filling Under GST</li>
                        </ul>
                    </div>
                </div>
                <div className="blog-details border-top pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  lutbgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                    </div>
                                </article>
                            </div>
                            <div className="col-lg-4">
                                <div className="blog-sidebar dot-bg ms-xxl-4 md-mt-60">
                                    <div className="categories bg-white bg-wrapper mb-30">
                                        <h5 className="mb-20">Other Services</h5>
                                        <ul className="style-none">
                                            {/* <li><Link href={"/services/GST_Registration/GST_registration"}>GST Registration</Link></li> */}
                                            <li><Link href={"/services/GST_Registration/LUT_filing_Under_GST"}>LUT Filling Under GST</Link></li>
                                            <li><Link href={"/services/GST_Registration/TDS-ReturnFiling"}>TDS Return Filing</Link></li>
                                            <li><Link href={"/services/GST_Registration/professionalTax_Registration"}>Professional Tax Registration</Link></li>
                                            <li><Link href={"/services/GST_Registration/providentFund"}>Provident Fund</Link></li>
                                            <li><Link href={"/services/GST_Registration/ESIS"}>ESIS</Link></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="div">
                            <p><b>Letter of Undertaking GST:</b></p>
                            <p>A Letter of Undertaking GST is a document that is used to register a company for GST. This document contains all the information required for the registration process, such as the company's name, address, contact details and other relevant information. It also includes an undertaking from the company to comply with all applicable GST laws and regulations. The Letter of Undertaking GST is an important document that must be completed in order to complete the registration process and ensure that your company is compliant with all applicable laws</p>
                            <p><b>Check List to File Letter of Undertaking the one who have GSTIN:</b></p>
                            <p>Filing a Letter of Undertaking (LUT) is an important part of the company registration process for those who have GSTIN. It is a document that states that the company will pay its taxes and comply with all applicable laws and regulations. Therefore, it is important to make sure that all documents are in order before filing the LUT. This article provides a checklist to help companies ensure they have everything they need to file their Letter of Undertaking successfully.</p>
                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="User Name" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="username@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
export default LUT_Under_GSt;