import Head from "next/head";

const FssaiRegistration = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-new.jpeg" />
            </Head>
            <div className="DSC">
                <div className="blog-details border-top mt-160 xl-mt-140 pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <div className="blog-post-meta mb-60 lg-mb-40">
                                    {/* <div className="post-info"><a href="blog_02.html">Rashed Kabir .</a> 6 min</div> */}
                                    <h3 className="blog-title">Fssai Registration</h3>
                                </div>
                            </div>
                        </div>
                        <div className="row gx-xl-5">
                            <div className="col-lg-12">
                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  figurebgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                        <p>Employee Provident Fund (EPF) is a retirement benefit scheme provided to employees in India. It is governed by the Employees' Provident Funds and Miscellaneous Provisions Act, 1952, and is managed by the Employees' Provident Fund Organization (EPFO), a statutory body under the Ministry of Labour and Employment, Government of India.</p>
                                        <div className="quote-wrapper">
                                            <div className="icon rounded-circle d-flex align-items-center justify-content-center m-auto"><img src="images/lazy.svg" data-src="images/icon/icon_67.svg" alt="" className="lazy-img" /></div>
                                            <div className="row">
                                                <div className="col-xxl-10 col-xl-11 col-lg-12 col-md-9 m-auto">
                                                    <h4>Quick solutions coupled with extraordinary nice performance—a recommendation that's great.</h4>
                                                </div>
                                            </div>
                                            <h6>James Bond. <span>USA</span></h6>
                                        </div>
                                    </div>
                                </article>
                            </div>
                        </div>
                        <div className="div">
                            <p>Here are some of the key features and provisions of the EPF scheme</p>
                            <p>
                                <b>Applicability :</b> The EPF scheme is applicable to all establishments employing 20 or more employees. However, establishments with less than 20 employees can also voluntarily opt for the scheme.
                            </p>
                            <p>
                                <b>Contributions :</b> Both the employer and the employee are required to make monthly contributions to the EPF account. The contribution rate for the employee is 12% of the basic salary and dearness allowance, while the employer contributes 12% of the employee's basic salary and dearness allowance.
                            </p>
                            <p>
                                <b>UAN :</b> Every employee enrolled under the EPF scheme is allotted a unique Universal Account Number (UAN). This number remains the same throughout the employee's career and can be used to track and manage the employee's EPF account.
                            </p>
                            <p>
                                <b>Interest rate :</b> The EPF contributions earn an interest rate which is determined by the government and notified by the EPFO every year. For the financial year 2020-21, the interest rate was 8.5%.
                            </p>
                            <p>
                                <b>Withdrawals :</b> Employees can withdraw their EPF balance for various purposes such as retirement, illness, marriage, education, house construction, etc., subject to certain conditions and Limitations.
                            </p>
                            <p>
                                <b>Nomination :</b> Employees are required to nominate a person or persons to receive the EPF balance in case of their death. The nomination can be changed at any time during the employee's career.
                            </p>
                            <p>
                                <b>Compliance :</b> Employers are required to register under the EPF scheme, obtain a code number, and maintain various registers and records related to EPF contributions and withdrawals. Employers who fail to comply with the provisions of the EPF Act can be penalized and prosecuted.
                            </p>
                            <p>
                                The EPF scheme is an important social security measure for employees in India, providing financial security and stability after retirement.
                            </p>
                            <p>
                                The EPF is popularly known as <b>PF</b>. It's a retirement saving scheme for all the salaried employees, is backed by the government on which fixed interest is paid.
                            </p>
                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="Rashed Kabir" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="rshdkabir@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </>
    )
}
export default FssaiRegistration;