import Head from "next/head";

const TDSReturnFiling = () => {
    return (
        <>
            <Head>
                <title>Rediger App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-new.jpeg" />
            </Head>
            <div className="DSC">
                <div className="blog-details border-top mt-160 xl-mt-140 pt-100 xl-pt-80 mb-150 xl-mb-100">
                    <div className="container">
                        <div className="row gx-xl-5">
                            <div className="col-lg-8">
                                <div className="blog-post-meta mb-60 lg-mb-40">
                                    {/* <div className="post-info"><a href="blog_02.html">Rashed Kabir .</a> 6 min</div> */}
                                    <h3 className="blog-title">TDS Return Filing</h3>
                                </div>
                            </div>
                        </div>
                        <div className="row gx-xl-5">
                            <div className="col-lg-12">
                                <article className="blog-post-meta">
                                    <figure className="post-img position-relative m0  figurebgImg">
                                        {/* <div className="fw-500 date d-inline-block">17 SEP</div> */}
                                    </figure>
                                    <div className="post-data pt-50 md-pt-30">
                                        <p><b>TDS Filing</b></p>
                                        <p>PLCs are required to deduct Tax Deducted at Source (TDS) while making payments to their vendors or suppliers. They are also required to file TDS payments to be done on monthly basis and Returns Quarterly basis.</p>
                                        <p>It is important for PLCs to comply with these annual compliances to avoid penalties and legal implications. PLCs can seek professional help Company Secretaries to ensure timely compliance with these requirements.</p>
                                        <div className="quote-wrapper">
                                            <div className="icon rounded-circle d-flex align-items-center justify-content-center m-auto"><img src="images/lazy.svg" data-src="images/icon/icon_67.svg" alt="" className="lazy-img" /></div>
                                            <div className="row">
                                                <div className="col-xxl-10 col-xl-11 col-lg-12 col-md-9 m-auto">
                                                    <h4>Quick solutions coupled with extraordinary nice performance—a recommendation that's great.</h4>
                                                </div>
                                            </div>
                                            <h6>James Bond. <span>USA</span></h6>
                                        </div>
                                    </div>
                                </article>
                            </div>
                        </div>
                        <div className="div">
                            <p><b>Documents to be submitted by Directors & Shareholders:</b></p>
                            <ul className="style-none list-item"><li>PAN Card (Compulsorily)
                            </li><li>Voters ID/ Passport/Driver’s License (Only any One as ID Proof)
                                </li><li>Copy of Latest Bank Statement (not older than 2 months old, to be used as Address Proof)
                                </li><li>Telephone or Mobile Bill/Electricity or Gas Bill (Utility bills) (to be used as Address Proof)
                                </li><li>Passport-size photograph (Soft copy)
                                </li><li>Copy of Specimen signature (Document shall be shared by us, and to be signed Directors Only)
                                </li></ul>
                        </div>
                        <div className="blog-comment-form mt-50">
                            <h3 className="blog-inner-title">Leave A Comment</h3>
                            <p><a href="#" data-bs-toggle="modal" data-bs-target="#loginModal" className="text-decoration-underline fw-500">Sign in</a> Sign-in to post your comment or signup if you don’t have any account.</p>
                            <form action="#" className="mt-30">
                                <div className="input-wrapper mb-30">
                                    <label>Name*</label>
                                    <input type="text" placeholder="Rashed Kabir" />
                                </div>
                                <div className="input-wrapper mb-40">
                                    <label>Email*</label>
                                    <input type="email" placeholder="rshdkabir@gmail.com" />
                                </div>
                                <div className="input-wrapper mb-30">
                                    <textarea placeholder="Your Comment"></textarea>
                                </div>
                                <button className="btn-five rounded-0">Post Comment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
export default TDSReturnFiling;